// <auto-generated />
namespace BackupStatus.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _003Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_003Create));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051345526_003-Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
